//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drivingSchool.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class academicPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public academicPlan()
        {
            this.certificate = new HashSet<certificate>();
        }
    
        public int id { get; set; }
        public int idSubject { get; set; }
        public int hours { get; set; }
        public Nullable<int> idCategory { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual category category { get; set; }
        public virtual subject subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<certificate> certificate { get; set; }
    }
}
