//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drivingSchool.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificate
    {
        public int id { get; set; }
        public int idStudent { get; set; }
        public int idPlan { get; set; }
        public int grade { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual academicPlan academicPlan { get; set; }
        public virtual student student { get; set; }
    }
}
