//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drivingSchool.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DrivingSchoolEntities_ : DbContext
    {
        public DrivingSchoolEntities_()
            : base("name=DrivingSchoolEntities_")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<academicPlan> academicPlan { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<certificate> certificate { get; set; }
        public virtual DbSet<contract> contract { get; set; }
        public virtual DbSet<group> group { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<subject> subject { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
